#line 2 "jsgf_scanner.c"

#line 4 "jsgf_scanner.c"

#define  yy_hlw_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define yy_hlw_FLEX_MAJOR_VERSION 2
#define yy_hlw_FLEX_MINOR_VERSION 5
#define yy_hlw_FLEX_SUBMINOR_VERSION 35
#if yy_hlw_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define yy_hlw_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define yy_hlw_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef yy_hlw_USE_CONST
#define yy_hlwconst const
#else
#define yy_hlwconst
#endif

/* Returned upon end-of-file. */
#define yy_hlw_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define yy_hlw_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef yy_hlw_TYPEDEF_yy_hlw_SCANNER_T
#define yy_hlw_TYPEDEF_yy_hlw_SCANNER_T
typedef void* yy_hlwscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yy_hlwin yy_hlwg->yy_hlwin_r
#define yy_hlwout yy_hlwg->yy_hlwout_r
#define yy_hlwextra yy_hlwg->yy_hlwextra_r
#define yy_hlwleng yy_hlwg->yy_hlwleng_r
#define yy_hlwtext yy_hlwg->yy_hlwtext_r
#define yy_hlwlineno (yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_bs_lineno)
#define yy_hlwcolumn (yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_bs_column)
#define yy_hlw_flex_debug yy_hlwg->yy_hlw_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_hlwg->yy_hlw_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The yy_hlwSTATE alias is for lex
 * compatibility.
 */
#define yy_hlw_START ((yy_hlwg->yy_hlw_start - 1) / 2)
#define yy_hlwSTATE yy_hlw_START

/* Action number for EOF rule of a given start state. */
#define yy_hlw_STATE_EOF(state) (yy_hlw_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define yy_hlw_NEW_FILE yy_hlwrestart(yy_hlwin ,yy_hlwscanner )

#define yy_hlw_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef yy_hlw_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, yy_hlw_BUF_SIZE is 2*yy_hlw_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define yy_hlw_BUF_SIZE 32768
#else
#define yy_hlw_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define yy_hlw_STATE_BUF_SIZE   ((yy_hlw_BUF_SIZE + 2) * sizeof(yy_hlw_state_type))

#ifndef yy_hlw_TYPEDEF_yy_hlw_BUFFER_STATE
#define yy_hlw_TYPEDEF_yy_hlw_BUFFER_STATE
typedef struct yy_hlw_buffer_state *yy_hlw_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define yy_hlw_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yy_hlwless(n) \
	do \
		{ \
		/* Undo effects of setting up yy_hlwtext. */ \
        int yy_hlwless_macro_arg = (n); \
        yy_hlw_LESS_LINENO(yy_hlwless_macro_arg);\
		*yy_hlw_cp = yy_hlwg->yy_hlw_hold_char; \
		yy_hlw_RESTORE_yy_hlw_MORE_OFFSET \
		yy_hlwg->yy_hlw_c_buf_p = yy_hlw_cp = yy_hlw_bp + yy_hlwless_macro_arg - yy_hlw_MORE_ADJ; \
		yy_hlw_DO_BEFORE_ACTION; /* set up yy_hlwtext again */ \
		} \
	while ( 0 )

#define unput(c) yy_hlwunput( c, yy_hlwg->yy_hlwtext_ptr , yy_hlwscanner )

#ifndef yy_hlw_TYPEDEF_yy_hlw_SIZE_T
#define yy_hlw_TYPEDEF_yy_hlw_SIZE_T
typedef size_t yy_hlw_size_t;
#endif

#ifndef yy_hlw_STRUCT_yy_hlw_BUFFER_STATE
#define yy_hlw_STRUCT_yy_hlw_BUFFER_STATE
struct yy_hlw_buffer_state
	{
	FILE *yy_hlw_input_file;

	char *yy_hlw_ch_buf;		/* input buffer */
	char *yy_hlw_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_hlw_size_t yy_hlw_buf_size;

	/* Number of characters read into yy_hlw_ch_buf, not including EOB
	 * characters.
	 */
	int yy_hlw_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_hlw_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_hlw_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_hlw_at_bol;

    int yy_hlw_bs_lineno; /**< The line count. */
    int yy_hlw_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_hlw_fill_buffer;

	int yy_hlw_buffer_status;

#define yy_hlw_BUFFER_NEW 0
#define yy_hlw_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as yy_hlw_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yy_hlwrestart()), so that the user can continue scanning by
	 * just pointing yy_hlwin at a new input file.
	 */
#define yy_hlw_BUFFER_EOF_PENDING 2

	};
#endif /* !yy_hlw_STRUCT_yy_hlw_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define yy_hlw_CURRENT_BUFFER ( yy_hlwg->yy_hlw_buffer_stack \
                          ? yy_hlwg->yy_hlw_buffer_stack[yy_hlwg->yy_hlw_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define yy_hlw_CURRENT_BUFFER_LVALUE yy_hlwg->yy_hlw_buffer_stack[yy_hlwg->yy_hlw_buffer_stack_top]

void yy_hlwrestart (FILE *input_file ,yy_hlwscan_t yy_hlwscanner );
void yy_hlw_switch_to_buffer (yy_hlw_BUFFER_STATE new_buffer ,yy_hlwscan_t yy_hlwscanner );
yy_hlw_BUFFER_STATE yy_hlw_create_buffer (FILE *file,int size ,yy_hlwscan_t yy_hlwscanner );
void yy_hlw_delete_buffer (yy_hlw_BUFFER_STATE b ,yy_hlwscan_t yy_hlwscanner );
void yy_hlw_flush_buffer (yy_hlw_BUFFER_STATE b ,yy_hlwscan_t yy_hlwscanner );
void yy_hlwpush_buffer_state (yy_hlw_BUFFER_STATE new_buffer ,yy_hlwscan_t yy_hlwscanner );
void yy_hlwpop_buffer_state (yy_hlwscan_t yy_hlwscanner );

static void yy_hlwensure_buffer_stack (yy_hlwscan_t yy_hlwscanner );
static void yy_hlw_load_buffer_state (yy_hlwscan_t yy_hlwscanner );
static void yy_hlw_init_buffer (yy_hlw_BUFFER_STATE b,FILE *file ,yy_hlwscan_t yy_hlwscanner );

#define yy_hlw_FLUSH_BUFFER yy_hlw_flush_buffer(yy_hlw_CURRENT_BUFFER ,yy_hlwscanner)

yy_hlw_BUFFER_STATE yy_hlw_scan_buffer (char *base,yy_hlw_size_t size ,yy_hlwscan_t yy_hlwscanner );
yy_hlw_BUFFER_STATE yy_hlw_scan_string (yy_hlwconst char *yy_hlw_str ,yy_hlwscan_t yy_hlwscanner );
yy_hlw_BUFFER_STATE yy_hlw_scan_bytes (yy_hlwconst char *bytes,int len ,yy_hlwscan_t yy_hlwscanner );

void *yy_hlwalloc (yy_hlw_size_t ,yy_hlwscan_t yy_hlwscanner );
void *yy_hlwrealloc (void *,yy_hlw_size_t ,yy_hlwscan_t yy_hlwscanner );
void yy_hlwfree (void * ,yy_hlwscan_t yy_hlwscanner );

#define yy_hlw_new_buffer yy_hlw_create_buffer

#define yy_hlw_set_interactive(is_interactive) \
	{ \
	if ( ! yy_hlw_CURRENT_BUFFER ){ \
        yy_hlwensure_buffer_stack (yy_hlwscanner); \
		yy_hlw_CURRENT_BUFFER_LVALUE =    \
            yy_hlw_create_buffer(yy_hlwin,yy_hlw_BUF_SIZE ,yy_hlwscanner); \
	} \
	yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_is_interactive = is_interactive; \
	}

#define yy_hlw_set_bol(at_bol) \
	{ \
	if ( ! yy_hlw_CURRENT_BUFFER ){\
        yy_hlwensure_buffer_stack (yy_hlwscanner); \
		yy_hlw_CURRENT_BUFFER_LVALUE =    \
            yy_hlw_create_buffer(yy_hlwin,yy_hlw_BUF_SIZE ,yy_hlwscanner); \
	} \
	yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_at_bol = at_bol; \
	}

#define yy_hlw_AT_BOL() (yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_at_bol)

/* Begin user sect3 */

#define yy_hlwwrap(n) 1
#define yy_hlw_SKIP_yy_hlwWRAP

typedef unsigned char yy_hlw_CHAR;

typedef int yy_hlw_state_type;

#define yy_hlwtext_ptr yy_hlwtext_r

static yy_hlw_state_type yy_hlw_get_previous_state (yy_hlwscan_t yy_hlwscanner );
static yy_hlw_state_type yy_hlw_try_NUL_trans (yy_hlw_state_type current_state  ,yy_hlwscan_t yy_hlwscanner);
static int yy_hlw_get_next_buffer (yy_hlwscan_t yy_hlwscanner );
static void yy_hlw_fatal_error (yy_hlwconst char msg[] ,yy_hlwscan_t yy_hlwscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yy_hlwtext.
 */
#define yy_hlw_DO_BEFORE_ACTION \
	yy_hlwg->yy_hlwtext_ptr = yy_hlw_bp; \
	yy_hlwleng = (size_t) (yy_hlw_cp - yy_hlw_bp); \
	yy_hlwg->yy_hlw_hold_char = *yy_hlw_cp; \
	*yy_hlw_cp = '\0'; \
	yy_hlwg->yy_hlw_c_buf_p = yy_hlw_cp;

#define yy_hlw_NUM_RULES 16
#define yy_hlw_END_OF_BUFFER 17
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_hlw_trans_info
	{
	flex_int32_t yy_hlw_verify;
	flex_int32_t yy_hlw_nxt;
	};
static yy_hlwconst flex_int16_t yy_hlw_accept[73] =
    {   0,
        0,    0,    0,    0,   17,   12,    1,    1,    1,   12,
       12,   15,   15,   15,   12,   12,   12,   15,    5,    1,
        5,   12,   12,    0,   12,   12,   12,    3,    0,   14,
        0,    0,   12,   12,   12,    0,    0,   11,    4,   13,
        0,   12,    0,   12,   12,   12,    0,    0,    2,   14,
       10,   12,   12,   12,    0,    0,   11,   13,    0,   12,
       12,   12,   12,    6,   12,   12,   12,   12,    8,    9,
        7,    0
    } ;

static yy_hlwconst flex_int32_t yy_hlw_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    7,
        7,    8,    7,    1,    1,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    7,   12,
        7,   13,    1,    1,    1,    1,    1,    1,    1,   14,
       15,    1,    1,   16,    1,    1,    1,    1,    1,    1,
        1,    1,   17,    1,    1,    1,    1,    1,    1,    1,
        7,   18,    7,    1,    1,    1,   19,   20,   21,    1,

        1,    1,   22,    1,   23,    1,    1,   24,   25,    1,
       26,   27,    1,   28,    1,   29,   30,    1,    1,    1,
        1,    1,   31,    7,   32,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yy_hlwconst flex_int32_t yy_hlw_meta[33] =
    {   0,
        1,    2,    2,    1,    1,    1,    2,    2,    1,    2,
        1,    3,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2
    } ;

static yy_hlwconst flex_int16_t yy_hlw_base[83] =
    {   0,
        0,    0,   31,   34,  133,    0,  193,  193,    0,   41,
      116,  193,   47,    0,  103,  105,   99,   29,  193,  193,
      118,    0,   72,   45,    0,  103,  110,  193,  115,  122,
       55,  111,  103,   93,   99,   44,   49,  193,  193,  193,
       65,    0,   73,    0,  134,  103,   30,  114,  193,  193,
      193,   89,   81,   74,   68,   91,   69,   84,   94,   82,
       70,   65,   69,    0,   69,   42,   48,   32,    0,    0,
        0,  193,  166,   44,  169,  172,  174,  177,  180,  183,
      186,  189
    } ;

static yy_hlwconst flex_int16_t yy_hlw_def[83] =
    {   0,
       72,    1,   73,   73,   72,   74,   72,   72,   74,   75,
       74,   72,   72,   76,   74,   74,   74,   77,   72,   72,
       72,   74,   75,   78,   74,   79,   74,   72,   72,   80,
       72,   76,   74,   74,   74,   77,   81,   72,   72,   72,
       82,   23,   78,   23,   79,   74,   72,   80,   72,   72,
       72,   74,   74,   74,   77,   81,   77,   78,   82,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,    0,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72
    } ;

static yy_hlwconst flex_int16_t yy_hlw_nxt[226] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   12,    6,   13,
        6,   14,   12,    6,    6,    6,    6,    6,    6,    6,
        6,   15,   16,    6,    6,    6,   17,    6,    6,    6,
       18,   12,   20,    8,   20,   20,    8,   20,   21,   50,
       47,   21,   24,   24,   22,   25,   37,   24,   24,   40,
       24,   36,   24,   24,   28,   29,   30,   31,   26,   71,
       38,   37,   41,   29,   50,   31,   56,   24,   70,   58,
       69,   24,   24,   24,   24,   38,   25,   40,   24,   24,
       57,   24,   59,   24,   24,   37,   37,   68,   40,   26,
       41,   67,   66,   36,   65,   64,   24,   63,   58,   38,

       38,   41,   24,   24,   43,   24,   62,   44,   56,   43,
       43,   59,   43,   61,   43,   43,   49,   60,   54,   53,
       45,   52,   57,   51,   49,   47,   46,   39,   35,   34,
       33,   27,   72,   43,   43,   43,   24,   72,   44,   72,
       43,   43,   72,   43,   72,   43,   43,   72,   72,   72,
       72,   45,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   43,   43,   19,   19,   19,   23,
       23,   23,   32,   32,   36,   36,   36,   24,   24,   24,
       42,   42,   42,   48,   48,   48,   55,   55,   55,   43,
       43,   43,    5,   72,   72,   72,   72,   72,   72,   72,

       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72
    } ;

static yy_hlwconst flex_int16_t yy_hlw_chk[226] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    4,    4,    4,    3,   47,
       47,    4,   10,   10,   74,   10,   18,   10,   10,   24,
       10,   37,   10,   10,   13,   13,   13,   13,   10,   68,
       18,   36,   24,   31,   31,   31,   37,   41,   67,   41,
       66,   10,   10,   23,   23,   36,   23,   43,   23,   23,
       37,   23,   41,   23,   23,   55,   57,   65,   58,   23,
       43,   63,   62,   56,   61,   60,   59,   54,   59,   55,

       57,   58,   23,   23,   26,   26,   53,   26,   56,   26,
       26,   59,   26,   52,   26,   26,   48,   46,   35,   34,
       26,   33,   56,   32,   30,   29,   27,   21,   17,   16,
       15,   11,    5,   26,   26,   45,   45,    0,   45,    0,
       45,   45,    0,   45,    0,   45,   45,    0,    0,    0,
        0,   45,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   45,   45,   73,   73,   73,   75,
       75,   75,   76,   76,   77,   77,   77,   78,   78,   78,
       79,   79,   79,   80,   80,   80,   81,   81,   81,   82,
       82,   82,   72,   72,   72,   72,   72,   72,   72,   72,

       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yy_hlwmore() yy_hlwmore_used_but_not_detected
#define yy_hlw_MORE_ADJ 0
#define yy_hlw_RESTORE_yy_hlw_MORE_OFFSET
#line 1 "_jsgf_scanner.l"
/* -*- mode: text -*- */
/* ====================================================================
 * Copyright (c) 2007 Carnegie Mellon University.  All rights
 * reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * This work was supported in part by funding from the Defense Advanced 
 * Research Projects Agency and the National Science Foundation of the 
 * United States of America, and the CMU Sphinx Speech Consortium.
 *
 * THIS SOFTWARE IS PROVIDED BY CARNEGIE MELLON UNIVERSITY ``AS IS'' AND 
 * ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
 * NOR ITS EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ====================================================================
 *
 */
/* YOU MUST USE FLEX 2.5.33 OR NEWER TO PROCESS THIS FILE!!! */
#line 39 "_jsgf_scanner.l"

#include "jsgf_internal.h"
#include "jsgf_parser.h"


#line 558 "jsgf_scanner.c"

#define INITIAL 0
#define COMMENT 1

#ifndef yy_hlw_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef yy_hlw_EXTRA_TYPE
#define yy_hlw_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yy_hlwguts_t
    {

    /* User-defined. Not touched by flex. */
    yy_hlw_EXTRA_TYPE yy_hlwextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yy_hlwin_r, *yy_hlwout_r;
    size_t yy_hlw_buffer_stack_top; /**< index of top of stack. */
    size_t yy_hlw_buffer_stack_max; /**< capacity of stack. */
    yy_hlw_BUFFER_STATE * yy_hlw_buffer_stack; /**< Stack as an array. */
    char yy_hlw_hold_char;
    int yy_hlw_n_chars;
    int yy_hlwleng_r;
    char *yy_hlw_c_buf_p;
    int yy_hlw_init;
    int yy_hlw_start;
    int yy_hlw_did_buffer_switch_on_eof;
    int yy_hlw_start_stack_ptr;
    int yy_hlw_start_stack_depth;
    int *yy_hlw_start_stack;
    yy_hlw_state_type yy_hlw_last_accepting_state;
    char* yy_hlw_last_accepting_cpos;

    int yy_hlwlineno_r;
    int yy_hlw_flex_debug_r;

    char *yy_hlwtext_r;
    int yy_hlw_more_flag;
    int yy_hlw_more_len;

    yy_hlwSTYPE * yy_hlwlval_r;

    }; /* end struct yy_hlwguts_t */

static int yy_hlw_init_globals (yy_hlwscan_t yy_hlwscanner );

    /* This must go here because yy_hlwSTYPE and yy_hlwLTYPE are included
     * from bison output in section 1.*/
    #    define yy_hlwlval yy_hlwg->yy_hlwlval_r
    
int yy_hlwlex_init (yy_hlwscan_t* scanner);

int yy_hlwlex_init_extra (yy_hlw_EXTRA_TYPE user_defined,yy_hlwscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yy_hlwlex_destroy (yy_hlwscan_t yy_hlwscanner );

int yy_hlwget_debug (yy_hlwscan_t yy_hlwscanner );

void yy_hlwset_debug (int debug_flag ,yy_hlwscan_t yy_hlwscanner );

yy_hlw_EXTRA_TYPE yy_hlwget_extra (yy_hlwscan_t yy_hlwscanner );

void yy_hlwset_extra (yy_hlw_EXTRA_TYPE user_defined ,yy_hlwscan_t yy_hlwscanner );

FILE *yy_hlwget_in (yy_hlwscan_t yy_hlwscanner );

void yy_hlwset_in  (FILE * in_str ,yy_hlwscan_t yy_hlwscanner );

FILE *yy_hlwget_out (yy_hlwscan_t yy_hlwscanner );

void yy_hlwset_out  (FILE * out_str ,yy_hlwscan_t yy_hlwscanner );

int yy_hlwget_leng (yy_hlwscan_t yy_hlwscanner );

char *yy_hlwget_text (yy_hlwscan_t yy_hlwscanner );

int yy_hlwget_lineno (yy_hlwscan_t yy_hlwscanner );

void yy_hlwset_lineno (int line_number ,yy_hlwscan_t yy_hlwscanner );

yy_hlwSTYPE * yy_hlwget_lval (yy_hlwscan_t yy_hlwscanner );

void yy_hlwset_lval (yy_hlwSTYPE * yy_hlwlval_param ,yy_hlwscan_t yy_hlwscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef yy_hlw_SKIP_yy_hlwWRAP
#ifdef __cplusplus
extern "C" int yy_hlwwrap (yy_hlwscan_t yy_hlwscanner );
#else
extern int yy_hlwwrap (yy_hlwscan_t yy_hlwscanner );
#endif
#endif

    static void yy_hlwunput (int c,char *buf_ptr  ,yy_hlwscan_t yy_hlwscanner);
    
#ifndef yy_hlwtext_ptr
static void yy_hlw_flex_strncpy (char *,yy_hlwconst char *,int ,yy_hlwscan_t yy_hlwscanner);
#endif

#ifdef yy_hlw_NEED_STRLEN
static int yy_hlw_flex_strlen (yy_hlwconst char * ,yy_hlwscan_t yy_hlwscanner);
#endif

#ifndef yy_hlw_NO_INPUT

#ifdef __cplusplus
static int yy_hlwinput (yy_hlwscan_t yy_hlwscanner );
#else
static int input (yy_hlwscan_t yy_hlwscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef yy_hlw_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define yy_hlw_READ_BUF_SIZE 16384
#else
#define yy_hlw_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yy_hlwtext, yy_hlwleng, 1, yy_hlwout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or yy_hlw_NULL,
 * is returned in "result".
 */
#ifndef yy_hlw_INPUT
#define yy_hlw_INPUT(buf,result,max_size) \
	if ( yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yy_hlwin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yy_hlwin ) ) \
			yy_hlw_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yy_hlwin))==0 && ferror(yy_hlwin)) \
			{ \
			if( errno != EINTR) \
				{ \
				yy_hlw_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yy_hlwin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yy_hlwterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yy_hlwterminate
#define yy_hlwterminate() return yy_hlw_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef yy_hlw_START_STACK_INCR
#define yy_hlw_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef yy_hlw_FATAL_ERROR
#define yy_hlw_FATAL_ERROR(msg) yy_hlw_fatal_error( msg , yy_hlwscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef yy_hlw_DECL
#define yy_hlw_DECL_IS_OURS 1

extern int yy_hlwlex \
               (yy_hlwSTYPE * yy_hlwlval_param ,yy_hlwscan_t yy_hlwscanner);

#define yy_hlw_DECL int yy_hlwlex \
               (yy_hlwSTYPE * yy_hlwlval_param , yy_hlwscan_t yy_hlwscanner)
#endif /* !yy_hlw_DECL */

/* Code executed at the beginning of each rule, after yy_hlwtext and yy_hlwleng
 * have been set up.
 */
#ifndef yy_hlw_USER_ACTION
#define yy_hlw_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef yy_hlw_BREAK
#define yy_hlw_BREAK break;
#endif

#define yy_hlw_RULE_SETUP \
	yy_hlw_USER_ACTION

/** The main scanner function which does all the work.
 */
yy_hlw_DECL
{
	register yy_hlw_state_type yy_hlw_current_state;
	register char *yy_hlw_cp, *yy_hlw_bp;
	register int yy_hlw_act;
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

#line 56 "_jsgf_scanner.l"


#line 800 "jsgf_scanner.c"

    yy_hlwlval = yy_hlwlval_param;

	if ( !yy_hlwg->yy_hlw_init )
		{
		yy_hlwg->yy_hlw_init = 1;

#ifdef yy_hlw_USER_INIT
		yy_hlw_USER_INIT;
#endif

		if ( ! yy_hlwg->yy_hlw_start )
			yy_hlwg->yy_hlw_start = 1;	/* first start state */

		if ( ! yy_hlwin )
			yy_hlwin = stdin;

		if ( ! yy_hlwout )
			yy_hlwout = stdout;

		if ( ! yy_hlw_CURRENT_BUFFER ) {
			yy_hlwensure_buffer_stack (yy_hlwscanner);
			yy_hlw_CURRENT_BUFFER_LVALUE =
				yy_hlw_create_buffer(yy_hlwin,yy_hlw_BUF_SIZE ,yy_hlwscanner);
		}

		yy_hlw_load_buffer_state(yy_hlwscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_hlw_cp = yy_hlwg->yy_hlw_c_buf_p;

		/* Support of yy_hlwtext. */
		*yy_hlw_cp = yy_hlwg->yy_hlw_hold_char;

		/* yy_hlw_bp points to the position in yy_hlw_ch_buf of the start of
		 * the current run.
		 */
		yy_hlw_bp = yy_hlw_cp;

		yy_hlw_current_state = yy_hlwg->yy_hlw_start;
yy_hlw_match:
		do
			{
			register yy_hlw_CHAR yy_hlw_c = yy_hlw_ec[yy_hlw_SC_TO_UI(*yy_hlw_cp)];
			if ( yy_hlw_accept[yy_hlw_current_state] )
				{
				yy_hlwg->yy_hlw_last_accepting_state = yy_hlw_current_state;
				yy_hlwg->yy_hlw_last_accepting_cpos = yy_hlw_cp;
				}
			while ( yy_hlw_chk[yy_hlw_base[yy_hlw_current_state] + yy_hlw_c] != yy_hlw_current_state )
				{
				yy_hlw_current_state = (int) yy_hlw_def[yy_hlw_current_state];
				if ( yy_hlw_current_state >= 73 )
					yy_hlw_c = yy_hlw_meta[(unsigned int) yy_hlw_c];
				}
			yy_hlw_current_state = yy_hlw_nxt[yy_hlw_base[yy_hlw_current_state] + (unsigned int) yy_hlw_c];
			++yy_hlw_cp;
			}
		while ( yy_hlw_base[yy_hlw_current_state] != 193 );

yy_hlw_find_action:
		yy_hlw_act = yy_hlw_accept[yy_hlw_current_state];
		if ( yy_hlw_act == 0 )
			{ /* have to back up */
			yy_hlw_cp = yy_hlwg->yy_hlw_last_accepting_cpos;
			yy_hlw_current_state = yy_hlwg->yy_hlw_last_accepting_state;
			yy_hlw_act = yy_hlw_accept[yy_hlw_current_state];
			}

		yy_hlw_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_hlw_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of yy_hlw_DO_BEFORE_ACTION */
			*yy_hlw_cp = yy_hlwg->yy_hlw_hold_char;
			yy_hlw_cp = yy_hlwg->yy_hlw_last_accepting_cpos;
			yy_hlw_current_state = yy_hlwg->yy_hlw_last_accepting_state;
			goto yy_hlw_find_action;

case 1:
/* rule 1 can match eol */
yy_hlw_RULE_SETUP
#line 58 "_jsgf_scanner.l"
;                     /* ignore whitespace */
	yy_hlw_BREAK
case 2:
/* rule 2 can match eol */
yy_hlw_RULE_SETUP
#line 59 "_jsgf_scanner.l"
;        /* single-line comments */
	yy_hlw_BREAK
case 3:
yy_hlw_RULE_SETUP
#line 60 "_jsgf_scanner.l"
{ BEGIN(COMMENT); } /* C-style comments */
	yy_hlw_BREAK
case 4:
yy_hlw_RULE_SETUP
#line 61 "_jsgf_scanner.l"
{ BEGIN(INITIAL); }
	yy_hlw_BREAK
case 5:
yy_hlw_RULE_SETUP
#line 62 "_jsgf_scanner.l"
;               /* Ignore stuff in comment mode */
	yy_hlw_BREAK
case 6:
yy_hlw_RULE_SETUP
#line 64 "_jsgf_scanner.l"
return HEADER;
	yy_hlw_BREAK
case 7:
yy_hlw_RULE_SETUP
#line 65 "_jsgf_scanner.l"
return GRAMMAR;
	yy_hlw_BREAK
case 8:
yy_hlw_RULE_SETUP
#line 66 "_jsgf_scanner.l"
return IMPORT;
	yy_hlw_BREAK
case 9:
yy_hlw_RULE_SETUP
#line 67 "_jsgf_scanner.l"
return PUBLIC;
	yy_hlw_BREAK
case 10:
/* rule 10 can match eol */
yy_hlw_RULE_SETUP
#line 69 "_jsgf_scanner.l"
{ yy_hlwlval->name = strdup(yy_hlwtext); return RULENAME; }
	yy_hlw_BREAK
case 11:
/* rule 11 can match eol */
yy_hlw_RULE_SETUP
#line 70 "_jsgf_scanner.l"
{ yy_hlwlval->name = strdup(yy_hlwtext); return TAG; }
	yy_hlw_BREAK
case 12:
yy_hlw_RULE_SETUP
#line 71 "_jsgf_scanner.l"
{ yy_hlwlval->name = strdup(yy_hlwtext); return TOKEN; }
	yy_hlw_BREAK
case 13:
/* rule 13 can match eol */
yy_hlw_RULE_SETUP
#line 72 "_jsgf_scanner.l"
{ yy_hlwlval->name = strdup(yy_hlwtext); return TOKEN; }
	yy_hlw_BREAK
case 14:
yy_hlw_RULE_SETUP
#line 73 "_jsgf_scanner.l"
{ yy_hlwlval->weight = atof_c(yy_hlwtext+1); return WEIGHT; }
	yy_hlw_BREAK
case 15:
yy_hlw_RULE_SETUP
#line 75 "_jsgf_scanner.l"
return yy_hlwtext[0];        /* Single-character tokens */
	yy_hlw_BREAK
case 16:
yy_hlw_RULE_SETUP
#line 77 "_jsgf_scanner.l"
ECHO;
	yy_hlw_BREAK
#line 970 "jsgf_scanner.c"
case yy_hlw_STATE_EOF(INITIAL):
case yy_hlw_STATE_EOF(COMMENT):
	yy_hlwterminate();

	case yy_hlw_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_hlw_amount_of_matched_text = (int) (yy_hlw_cp - yy_hlwg->yy_hlwtext_ptr) - 1;

		/* Undo the effects of yy_hlw_DO_BEFORE_ACTION. */
		*yy_hlw_cp = yy_hlwg->yy_hlw_hold_char;
		yy_hlw_RESTORE_yy_hlw_MORE_OFFSET

		if ( yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buffer_status == yy_hlw_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yy_hlwin at a new source and called
			 * yy_hlwlex().  If so, then we have to assure
			 * consistency between yy_hlw_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_hlwg->yy_hlw_n_chars = yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_n_chars;
			yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_input_file = yy_hlwin;
			yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buffer_status = yy_hlw_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_hlw_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_hlw_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_hlwg->yy_hlw_c_buf_p <= &yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[yy_hlwg->yy_hlw_n_chars] )
			{ /* This was really a NUL. */
			yy_hlw_state_type yy_hlw_next_state;

			yy_hlwg->yy_hlw_c_buf_p = yy_hlwg->yy_hlwtext_ptr + yy_hlw_amount_of_matched_text;

			yy_hlw_current_state = yy_hlw_get_previous_state( yy_hlwscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_hlw_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_hlw_next_state = yy_hlw_try_NUL_trans( yy_hlw_current_state , yy_hlwscanner);

			yy_hlw_bp = yy_hlwg->yy_hlwtext_ptr + yy_hlw_MORE_ADJ;

			if ( yy_hlw_next_state )
				{
				/* Consume the NUL. */
				yy_hlw_cp = ++yy_hlwg->yy_hlw_c_buf_p;
				yy_hlw_current_state = yy_hlw_next_state;
				goto yy_hlw_match;
				}

			else
				{
				yy_hlw_cp = yy_hlwg->yy_hlw_c_buf_p;
				goto yy_hlw_find_action;
				}
			}

		else switch ( yy_hlw_get_next_buffer( yy_hlwscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_hlwg->yy_hlw_did_buffer_switch_on_eof = 0;

				if ( yy_hlwwrap(yy_hlwscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_hlw_get_next_buffer() to have set up
					 * yy_hlwtext, we can now set up
					 * yy_hlw_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * yy_hlw_NULL, it'll still work - another
					 * yy_hlw_NULL will get returned.
					 */
					yy_hlwg->yy_hlw_c_buf_p = yy_hlwg->yy_hlwtext_ptr + yy_hlw_MORE_ADJ;

					yy_hlw_act = yy_hlw_STATE_EOF(yy_hlw_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_hlwg->yy_hlw_did_buffer_switch_on_eof )
						yy_hlw_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_hlwg->yy_hlw_c_buf_p =
					yy_hlwg->yy_hlwtext_ptr + yy_hlw_amount_of_matched_text;

				yy_hlw_current_state = yy_hlw_get_previous_state( yy_hlwscanner );

				yy_hlw_cp = yy_hlwg->yy_hlw_c_buf_p;
				yy_hlw_bp = yy_hlwg->yy_hlwtext_ptr + yy_hlw_MORE_ADJ;
				goto yy_hlw_match;

			case EOB_ACT_LAST_MATCH:
				yy_hlwg->yy_hlw_c_buf_p =
				&yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[yy_hlwg->yy_hlw_n_chars];

				yy_hlw_current_state = yy_hlw_get_previous_state( yy_hlwscanner );

				yy_hlw_cp = yy_hlwg->yy_hlw_c_buf_p;
				yy_hlw_bp = yy_hlwg->yy_hlwtext_ptr + yy_hlw_MORE_ADJ;
				goto yy_hlw_find_action;
			}
		break;
		}

	default:
		yy_hlw_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yy_hlwlex */

/* yy_hlw_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_hlw_get_next_buffer (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
	register char *dest = yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf;
	register char *source = yy_hlwg->yy_hlwtext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_hlwg->yy_hlw_c_buf_p > &yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[yy_hlwg->yy_hlw_n_chars + 1] )
		yy_hlw_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_hlwg->yy_hlw_c_buf_p - yy_hlwg->yy_hlwtext_ptr - yy_hlw_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_hlwg->yy_hlw_c_buf_p - yy_hlwg->yy_hlwtext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buffer_status == yy_hlw_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_n_chars = yy_hlwg->yy_hlw_n_chars = 0;

	else
		{
			int num_to_read =
			yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			yy_hlw_BUFFER_STATE b = yy_hlw_CURRENT_BUFFER;

			int yy_hlw_c_buf_p_offset =
				(int) (yy_hlwg->yy_hlw_c_buf_p - b->yy_hlw_ch_buf);

			if ( b->yy_hlw_is_our_buffer )
				{
				int new_size = b->yy_hlw_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_hlw_buf_size += b->yy_hlw_buf_size / 8;
				else
					b->yy_hlw_buf_size *= 2;

				b->yy_hlw_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_hlwrealloc((void *) b->yy_hlw_ch_buf,b->yy_hlw_buf_size + 2 ,yy_hlwscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_hlw_ch_buf = 0;

			if ( ! b->yy_hlw_ch_buf )
				yy_hlw_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_hlwg->yy_hlw_c_buf_p = &b->yy_hlw_ch_buf[yy_hlw_c_buf_p_offset];

			num_to_read = yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > yy_hlw_READ_BUF_SIZE )
			num_to_read = yy_hlw_READ_BUF_SIZE;

		/* Read in more data. */
		yy_hlw_INPUT( (&yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[number_to_move]),
			yy_hlwg->yy_hlw_n_chars, (size_t) num_to_read );

		yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_n_chars = yy_hlwg->yy_hlw_n_chars;
		}

	if ( yy_hlwg->yy_hlw_n_chars == 0 )
		{
		if ( number_to_move == yy_hlw_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yy_hlwrestart(yy_hlwin  ,yy_hlwscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buffer_status =
				yy_hlw_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_hlw_size_t) (yy_hlwg->yy_hlw_n_chars + number_to_move) > yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_hlw_size_t new_size = yy_hlwg->yy_hlw_n_chars + number_to_move + (yy_hlwg->yy_hlw_n_chars >> 1);
		yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf = (char *) yy_hlwrealloc((void *) yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf,new_size ,yy_hlwscanner );
		if ( ! yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf )
			yy_hlw_FATAL_ERROR( "out of dynamic memory in yy_hlw_get_next_buffer()" );
	}

	yy_hlwg->yy_hlw_n_chars += number_to_move;
	yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[yy_hlwg->yy_hlw_n_chars] = yy_hlw_END_OF_BUFFER_CHAR;
	yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[yy_hlwg->yy_hlw_n_chars + 1] = yy_hlw_END_OF_BUFFER_CHAR;

	yy_hlwg->yy_hlwtext_ptr = &yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[0];

	return ret_val;
}

/* yy_hlw_get_previous_state - get the state just before the EOB char was reached */

    static yy_hlw_state_type yy_hlw_get_previous_state (yy_hlwscan_t yy_hlwscanner)
{
	register yy_hlw_state_type yy_hlw_current_state;
	register char *yy_hlw_cp;
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

	yy_hlw_current_state = yy_hlwg->yy_hlw_start;

	for ( yy_hlw_cp = yy_hlwg->yy_hlwtext_ptr + yy_hlw_MORE_ADJ; yy_hlw_cp < yy_hlwg->yy_hlw_c_buf_p; ++yy_hlw_cp )
		{
		register yy_hlw_CHAR yy_hlw_c = (*yy_hlw_cp ? yy_hlw_ec[yy_hlw_SC_TO_UI(*yy_hlw_cp)] : 1);
		if ( yy_hlw_accept[yy_hlw_current_state] )
			{
			yy_hlwg->yy_hlw_last_accepting_state = yy_hlw_current_state;
			yy_hlwg->yy_hlw_last_accepting_cpos = yy_hlw_cp;
			}
		while ( yy_hlw_chk[yy_hlw_base[yy_hlw_current_state] + yy_hlw_c] != yy_hlw_current_state )
			{
			yy_hlw_current_state = (int) yy_hlw_def[yy_hlw_current_state];
			if ( yy_hlw_current_state >= 73 )
				yy_hlw_c = yy_hlw_meta[(unsigned int) yy_hlw_c];
			}
		yy_hlw_current_state = yy_hlw_nxt[yy_hlw_base[yy_hlw_current_state] + (unsigned int) yy_hlw_c];
		}

	return yy_hlw_current_state;
}

/* yy_hlw_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_hlw_try_NUL_trans( current_state );
 */
    static yy_hlw_state_type yy_hlw_try_NUL_trans  (yy_hlw_state_type yy_hlw_current_state , yy_hlwscan_t yy_hlwscanner)
{
	register int yy_hlw_is_jam;
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner; /* This var may be unused depending upon options. */
	register char *yy_hlw_cp = yy_hlwg->yy_hlw_c_buf_p;

	register yy_hlw_CHAR yy_hlw_c = 1;
	if ( yy_hlw_accept[yy_hlw_current_state] )
		{
		yy_hlwg->yy_hlw_last_accepting_state = yy_hlw_current_state;
		yy_hlwg->yy_hlw_last_accepting_cpos = yy_hlw_cp;
		}
	while ( yy_hlw_chk[yy_hlw_base[yy_hlw_current_state] + yy_hlw_c] != yy_hlw_current_state )
		{
		yy_hlw_current_state = (int) yy_hlw_def[yy_hlw_current_state];
		if ( yy_hlw_current_state >= 73 )
			yy_hlw_c = yy_hlw_meta[(unsigned int) yy_hlw_c];
		}
	yy_hlw_current_state = yy_hlw_nxt[yy_hlw_base[yy_hlw_current_state] + (unsigned int) yy_hlw_c];
	yy_hlw_is_jam = (yy_hlw_current_state == 72);

	return yy_hlw_is_jam ? 0 : yy_hlw_current_state;
}

    static void yy_hlwunput (int c, register char * yy_hlw_bp , yy_hlwscan_t yy_hlwscanner)
{
	register char *yy_hlw_cp;
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

    yy_hlw_cp = yy_hlwg->yy_hlw_c_buf_p;

	/* undo effects of setting up yy_hlwtext */
	*yy_hlw_cp = yy_hlwg->yy_hlw_hold_char;

	if ( yy_hlw_cp < yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_hlwg->yy_hlw_n_chars + 2;
		register char *dest = &yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[
					yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buf_size + 2];
		register char *source =
				&yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[number_to_move];

		while ( source > yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf )
			*--dest = *--source;

		yy_hlw_cp += (int) (dest - source);
		yy_hlw_bp += (int) (dest - source);
		yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_n_chars =
			yy_hlwg->yy_hlw_n_chars = yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buf_size;

		if ( yy_hlw_cp < yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf + 2 )
			yy_hlw_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_hlw_cp = (char) c;

	yy_hlwg->yy_hlwtext_ptr = yy_hlw_bp;
	yy_hlwg->yy_hlw_hold_char = *yy_hlw_cp;
	yy_hlwg->yy_hlw_c_buf_p = yy_hlw_cp;
}

#ifndef yy_hlw_NO_INPUT
#ifdef __cplusplus
    static int yy_hlwinput (yy_hlwscan_t yy_hlwscanner)
#else
    static int input  (yy_hlwscan_t yy_hlwscanner)
#endif

{
	int c;
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

	*yy_hlwg->yy_hlw_c_buf_p = yy_hlwg->yy_hlw_hold_char;

	if ( *yy_hlwg->yy_hlw_c_buf_p == yy_hlw_END_OF_BUFFER_CHAR )
		{
		/* yy_hlw_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_hlwg->yy_hlw_c_buf_p < &yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_ch_buf[yy_hlwg->yy_hlw_n_chars] )
			/* This was really a NUL. */
			*yy_hlwg->yy_hlw_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_hlwg->yy_hlw_c_buf_p - yy_hlwg->yy_hlwtext_ptr;
			++yy_hlwg->yy_hlw_c_buf_p;

			switch ( yy_hlw_get_next_buffer( yy_hlwscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_hlw_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yy_hlwrestart(yy_hlwin ,yy_hlwscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yy_hlwwrap(yy_hlwscanner ) )
						return EOF;

					if ( ! yy_hlwg->yy_hlw_did_buffer_switch_on_eof )
						yy_hlw_NEW_FILE;
#ifdef __cplusplus
					return yy_hlwinput(yy_hlwscanner);
#else
					return input(yy_hlwscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_hlwg->yy_hlw_c_buf_p = yy_hlwg->yy_hlwtext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_hlwg->yy_hlw_c_buf_p;	/* cast for 8-bit char's */
	*yy_hlwg->yy_hlw_c_buf_p = '\0';	/* preserve yy_hlwtext */
	yy_hlwg->yy_hlw_hold_char = *++yy_hlwg->yy_hlw_c_buf_p;

	return c;
}
#endif	/* ifndef yy_hlw_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yy_hlwscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yy_hlwrestart  (FILE * input_file , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

	if ( ! yy_hlw_CURRENT_BUFFER ){
        yy_hlwensure_buffer_stack (yy_hlwscanner);
		yy_hlw_CURRENT_BUFFER_LVALUE =
            yy_hlw_create_buffer(yy_hlwin,yy_hlw_BUF_SIZE ,yy_hlwscanner);
	}

	yy_hlw_init_buffer(yy_hlw_CURRENT_BUFFER,input_file ,yy_hlwscanner);
	yy_hlw_load_buffer_state(yy_hlwscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yy_hlwscanner The scanner object.
 */
    void yy_hlw_switch_to_buffer  (yy_hlw_BUFFER_STATE  new_buffer , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yy_hlwpop_buffer_state();
	 *		yy_hlwpush_buffer_state(new_buffer);
     */
	yy_hlwensure_buffer_stack (yy_hlwscanner);
	if ( yy_hlw_CURRENT_BUFFER == new_buffer )
		return;

	if ( yy_hlw_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yy_hlwg->yy_hlw_c_buf_p = yy_hlwg->yy_hlw_hold_char;
		yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buf_pos = yy_hlwg->yy_hlw_c_buf_p;
		yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_n_chars = yy_hlwg->yy_hlw_n_chars;
		}

	yy_hlw_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_hlw_load_buffer_state(yy_hlwscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yy_hlwwrap()) processing, but the only time this flag
	 * is looked at is after yy_hlwwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_hlwg->yy_hlw_did_buffer_switch_on_eof = 1;
}

static void yy_hlw_load_buffer_state  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
	yy_hlwg->yy_hlw_n_chars = yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_n_chars;
	yy_hlwg->yy_hlwtext_ptr = yy_hlwg->yy_hlw_c_buf_p = yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buf_pos;
	yy_hlwin = yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_input_file;
	yy_hlwg->yy_hlw_hold_char = *yy_hlwg->yy_hlw_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c yy_hlw_BUF_SIZE.
 * @param yy_hlwscanner The scanner object.
 * @return the allocated buffer state.
 */
    yy_hlw_BUFFER_STATE yy_hlw_create_buffer  (FILE * file, int  size , yy_hlwscan_t yy_hlwscanner)
{
	yy_hlw_BUFFER_STATE b;
    
	b = (yy_hlw_BUFFER_STATE) yy_hlwalloc(sizeof( struct yy_hlw_buffer_state ) ,yy_hlwscanner );
	if ( ! b )
		yy_hlw_FATAL_ERROR( "out of dynamic memory in yy_hlw_create_buffer()" );

	b->yy_hlw_buf_size = size;

	/* yy_hlw_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_hlw_ch_buf = (char *) yy_hlwalloc(b->yy_hlw_buf_size + 2 ,yy_hlwscanner );
	if ( ! b->yy_hlw_ch_buf )
		yy_hlw_FATAL_ERROR( "out of dynamic memory in yy_hlw_create_buffer()" );

	b->yy_hlw_is_our_buffer = 1;

	yy_hlw_init_buffer(b,file ,yy_hlwscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_hlw_create_buffer()
 * @param yy_hlwscanner The scanner object.
 */
    void yy_hlw_delete_buffer (yy_hlw_BUFFER_STATE  b , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

	if ( ! b )
		return;

	if ( b == yy_hlw_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		yy_hlw_CURRENT_BUFFER_LVALUE = (yy_hlw_BUFFER_STATE) 0;

	if ( b->yy_hlw_is_our_buffer )
		yy_hlwfree((void *) b->yy_hlw_ch_buf ,yy_hlwscanner );

	yy_hlwfree((void *) b ,yy_hlwscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yy_hlwrestart() or at EOF.
 */
    static void yy_hlw_init_buffer  (yy_hlw_BUFFER_STATE  b, FILE * file , yy_hlwscan_t yy_hlwscanner)

{
	int oerrno = errno;
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

	yy_hlw_flush_buffer(b ,yy_hlwscanner);

	b->yy_hlw_input_file = file;
	b->yy_hlw_fill_buffer = 1;

    /* If b is the current buffer, then yy_hlw_init_buffer was _probably_
     * called from yy_hlwrestart() or through yy_hlw_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != yy_hlw_CURRENT_BUFFER){
        b->yy_hlw_bs_lineno = 1;
        b->yy_hlw_bs_column = 0;
    }

        b->yy_hlw_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, yy_hlw_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c yy_hlw_CURRENT_BUFFER.
 * @param yy_hlwscanner The scanner object.
 */
    void yy_hlw_flush_buffer (yy_hlw_BUFFER_STATE  b , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
	if ( ! b )
		return;

	b->yy_hlw_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_hlw_ch_buf[0] = yy_hlw_END_OF_BUFFER_CHAR;
	b->yy_hlw_ch_buf[1] = yy_hlw_END_OF_BUFFER_CHAR;

	b->yy_hlw_buf_pos = &b->yy_hlw_ch_buf[0];

	b->yy_hlw_at_bol = 1;
	b->yy_hlw_buffer_status = yy_hlw_BUFFER_NEW;

	if ( b == yy_hlw_CURRENT_BUFFER )
		yy_hlw_load_buffer_state(yy_hlwscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yy_hlwscanner The scanner object.
 */
void yy_hlwpush_buffer_state (yy_hlw_BUFFER_STATE new_buffer , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
	if (new_buffer == NULL)
		return;

	yy_hlwensure_buffer_stack(yy_hlwscanner);

	/* This block is copied from yy_hlw_switch_to_buffer. */
	if ( yy_hlw_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yy_hlwg->yy_hlw_c_buf_p = yy_hlwg->yy_hlw_hold_char;
		yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_buf_pos = yy_hlwg->yy_hlw_c_buf_p;
		yy_hlw_CURRENT_BUFFER_LVALUE->yy_hlw_n_chars = yy_hlwg->yy_hlw_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (yy_hlw_CURRENT_BUFFER)
		yy_hlwg->yy_hlw_buffer_stack_top++;
	yy_hlw_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_hlw_switch_to_buffer. */
	yy_hlw_load_buffer_state(yy_hlwscanner );
	yy_hlwg->yy_hlw_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yy_hlwscanner The scanner object.
 */
void yy_hlwpop_buffer_state (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
	if (!yy_hlw_CURRENT_BUFFER)
		return;

	yy_hlw_delete_buffer(yy_hlw_CURRENT_BUFFER ,yy_hlwscanner);
	yy_hlw_CURRENT_BUFFER_LVALUE = NULL;
	if (yy_hlwg->yy_hlw_buffer_stack_top > 0)
		--yy_hlwg->yy_hlw_buffer_stack_top;

	if (yy_hlw_CURRENT_BUFFER) {
		yy_hlw_load_buffer_state(yy_hlwscanner );
		yy_hlwg->yy_hlw_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yy_hlwensure_buffer_stack (yy_hlwscan_t yy_hlwscanner)
{
	int num_to_alloc;
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

	if (!yy_hlwg->yy_hlw_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yy_hlwg->yy_hlw_buffer_stack = (struct yy_hlw_buffer_state**)yy_hlwalloc
								(num_to_alloc * sizeof(struct yy_hlw_buffer_state*)
								, yy_hlwscanner);
		if ( ! yy_hlwg->yy_hlw_buffer_stack )
			yy_hlw_FATAL_ERROR( "out of dynamic memory in yy_hlwensure_buffer_stack()" );
								  
		memset(yy_hlwg->yy_hlw_buffer_stack, 0, num_to_alloc * sizeof(struct yy_hlw_buffer_state*));
				
		yy_hlwg->yy_hlw_buffer_stack_max = num_to_alloc;
		yy_hlwg->yy_hlw_buffer_stack_top = 0;
		return;
	}

	if (yy_hlwg->yy_hlw_buffer_stack_top >= (yy_hlwg->yy_hlw_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yy_hlwg->yy_hlw_buffer_stack_max + grow_size;
		yy_hlwg->yy_hlw_buffer_stack = (struct yy_hlw_buffer_state**)yy_hlwrealloc
								(yy_hlwg->yy_hlw_buffer_stack,
								num_to_alloc * sizeof(struct yy_hlw_buffer_state*)
								, yy_hlwscanner);
		if ( ! yy_hlwg->yy_hlw_buffer_stack )
			yy_hlw_FATAL_ERROR( "out of dynamic memory in yy_hlwensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yy_hlwg->yy_hlw_buffer_stack + yy_hlwg->yy_hlw_buffer_stack_max, 0, grow_size * sizeof(struct yy_hlw_buffer_state*));
		yy_hlwg->yy_hlw_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yy_hlwscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
yy_hlw_BUFFER_STATE yy_hlw_scan_buffer  (char * base, yy_hlw_size_t  size , yy_hlwscan_t yy_hlwscanner)
{
	yy_hlw_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != yy_hlw_END_OF_BUFFER_CHAR ||
	     base[size-1] != yy_hlw_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (yy_hlw_BUFFER_STATE) yy_hlwalloc(sizeof( struct yy_hlw_buffer_state ) ,yy_hlwscanner );
	if ( ! b )
		yy_hlw_FATAL_ERROR( "out of dynamic memory in yy_hlw_scan_buffer()" );

	b->yy_hlw_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_hlw_buf_pos = b->yy_hlw_ch_buf = base;
	b->yy_hlw_is_our_buffer = 0;
	b->yy_hlw_input_file = 0;
	b->yy_hlw_n_chars = b->yy_hlw_buf_size;
	b->yy_hlw_is_interactive = 0;
	b->yy_hlw_at_bol = 1;
	b->yy_hlw_fill_buffer = 0;
	b->yy_hlw_buffer_status = yy_hlw_BUFFER_NEW;

	yy_hlw_switch_to_buffer(b ,yy_hlwscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yy_hlwlex() will
 * scan from a @e copy of @a str.
 * @param yy_hlwstr a NUL-terminated string to scan
 * @param yy_hlwscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_hlw_scan_bytes() instead.
 */
yy_hlw_BUFFER_STATE yy_hlw_scan_string (yy_hlwconst char * yy_hlwstr , yy_hlwscan_t yy_hlwscanner)
{
    
	return yy_hlw_scan_bytes(yy_hlwstr,strlen(yy_hlwstr) ,yy_hlwscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yy_hlwlex() will
 * scan from a @e copy of @a bytes.
 * @param yy_hlwbytes the byte buffer to scan
 * @param _yy_hlwbytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yy_hlwscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
yy_hlw_BUFFER_STATE yy_hlw_scan_bytes  (yy_hlwconst char * yy_hlwbytes, int  _yy_hlwbytes_len , yy_hlwscan_t yy_hlwscanner)
{
	yy_hlw_BUFFER_STATE b;
	char *buf;
	yy_hlw_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yy_hlwbytes_len + 2;
	buf = (char *) yy_hlwalloc(n ,yy_hlwscanner );
	if ( ! buf )
		yy_hlw_FATAL_ERROR( "out of dynamic memory in yy_hlw_scan_bytes()" );

	for ( i = 0; i < _yy_hlwbytes_len; ++i )
		buf[i] = yy_hlwbytes[i];

	buf[_yy_hlwbytes_len] = buf[_yy_hlwbytes_len+1] = yy_hlw_END_OF_BUFFER_CHAR;

	b = yy_hlw_scan_buffer(buf,n ,yy_hlwscanner);
	if ( ! b )
		yy_hlw_FATAL_ERROR( "bad buffer in yy_hlw_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_hlw_is_our_buffer = 1;

	return b;
}

#ifndef yy_hlw_EXIT_FAILURE
#define yy_hlw_EXIT_FAILURE 2
#endif

static void yy_hlw_fatal_error (yy_hlwconst char* msg , yy_hlwscan_t yy_hlwscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( yy_hlw_EXIT_FAILURE );
}

/* Redefine yy_hlwless() so it works in section 3 code. */

#undef yy_hlwless
#define yy_hlwless(n) \
	do \
		{ \
		/* Undo effects of setting up yy_hlwtext. */ \
        int yy_hlwless_macro_arg = (n); \
        yy_hlw_LESS_LINENO(yy_hlwless_macro_arg);\
		yy_hlwtext[yy_hlwleng] = yy_hlwg->yy_hlw_hold_char; \
		yy_hlwg->yy_hlw_c_buf_p = yy_hlwtext + yy_hlwless_macro_arg; \
		yy_hlwg->yy_hlw_hold_char = *yy_hlwg->yy_hlw_c_buf_p; \
		*yy_hlwg->yy_hlw_c_buf_p = '\0'; \
		yy_hlwleng = yy_hlwless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yy_hlwscanner The scanner object.
 */
yy_hlw_EXTRA_TYPE yy_hlwget_extra  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    return yy_hlwextra;
}

/** Get the current line number.
 * @param yy_hlwscanner The scanner object.
 */
int yy_hlwget_lineno  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    
        if (! yy_hlw_CURRENT_BUFFER)
            return 0;
    
    return yy_hlwlineno;
}

/** Get the current column number.
 * @param yy_hlwscanner The scanner object.
 */
int yy_hlwget_column  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    
        if (! yy_hlw_CURRENT_BUFFER)
            return 0;
    
    return yy_hlwcolumn;
}

/** Get the input stream.
 * @param yy_hlwscanner The scanner object.
 */
FILE *yy_hlwget_in  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    return yy_hlwin;
}

/** Get the output stream.
 * @param yy_hlwscanner The scanner object.
 */
FILE *yy_hlwget_out  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    return yy_hlwout;
}

/** Get the length of the current token.
 * @param yy_hlwscanner The scanner object.
 */
int yy_hlwget_leng  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    return yy_hlwleng;
}

/** Get the current token.
 * @param yy_hlwscanner The scanner object.
 */

char *yy_hlwget_text  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    return yy_hlwtext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yy_hlwscanner The scanner object.
 */
void yy_hlwset_extra (yy_hlw_EXTRA_TYPE  user_defined , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    yy_hlwextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yy_hlwscanner The scanner object.
 */
void yy_hlwset_lineno (int  line_number , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! yy_hlw_CURRENT_BUFFER )
           yy_hlw_fatal_error( "yy_hlwset_lineno called with no buffer" , yy_hlwscanner); 
    
    yy_hlwlineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yy_hlwscanner The scanner object.
 */
void yy_hlwset_column (int  column_no , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

        /* column is only valid if an input buffer exists. */
        if (! yy_hlw_CURRENT_BUFFER )
           yy_hlw_fatal_error( "yy_hlwset_column called with no buffer" , yy_hlwscanner); 
    
    yy_hlwcolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yy_hlwscanner The scanner object.
 * @see yy_hlw_switch_to_buffer
 */
void yy_hlwset_in (FILE *  in_str , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    yy_hlwin = in_str ;
}

void yy_hlwset_out (FILE *  out_str , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    yy_hlwout = out_str ;
}

int yy_hlwget_debug  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    return yy_hlw_flex_debug;
}

void yy_hlwset_debug (int  bdebug , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    yy_hlw_flex_debug = bdebug ;
}

/* Accessor methods for yy_hlwlval and yy_hlwlloc */

yy_hlwSTYPE * yy_hlwget_lval  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    return yy_hlwlval;
}

void yy_hlwset_lval (yy_hlwSTYPE *  yy_hlwlval_param , yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    yy_hlwlval = yy_hlwlval_param;
}

/* User-visible API */

/* yy_hlwlex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yy_hlwlex_init(yy_hlwscan_t* ptr_yy_hlw_globals)

{
    if (ptr_yy_hlw_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_hlw_globals = (yy_hlwscan_t) yy_hlwalloc ( sizeof( struct yy_hlwguts_t ), NULL );

    if (*ptr_yy_hlw_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_hlw_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_hlw_globals,0x00,sizeof(struct yy_hlwguts_t));

    return yy_hlw_init_globals ( *ptr_yy_hlw_globals );
}

/* yy_hlwlex_init_extra has the same functionality as yy_hlwlex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yy_hlwalloc in
 * the yy_hlwextra field.
 */

int yy_hlwlex_init_extra(yy_hlw_EXTRA_TYPE yy_hlw_user_defined,yy_hlwscan_t* ptr_yy_hlw_globals )

{
    struct yy_hlwguts_t dummy_yy_hlwguts;

    yy_hlwset_extra (yy_hlw_user_defined, &dummy_yy_hlwguts);

    if (ptr_yy_hlw_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_hlw_globals = (yy_hlwscan_t) yy_hlwalloc ( sizeof( struct yy_hlwguts_t ), &dummy_yy_hlwguts );
	
    if (*ptr_yy_hlw_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_hlw_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_hlw_globals,0x00,sizeof(struct yy_hlwguts_t));
    
    yy_hlwset_extra (yy_hlw_user_defined, *ptr_yy_hlw_globals);
    
    return yy_hlw_init_globals ( *ptr_yy_hlw_globals );
}

static int yy_hlw_init_globals (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yy_hlwlex_destroy(), so don't allocate here.
     */

    yy_hlwg->yy_hlw_buffer_stack = 0;
    yy_hlwg->yy_hlw_buffer_stack_top = 0;
    yy_hlwg->yy_hlw_buffer_stack_max = 0;
    yy_hlwg->yy_hlw_c_buf_p = (char *) 0;
    yy_hlwg->yy_hlw_init = 0;
    yy_hlwg->yy_hlw_start = 0;

    yy_hlwg->yy_hlw_start_stack_ptr = 0;
    yy_hlwg->yy_hlw_start_stack_depth = 0;
    yy_hlwg->yy_hlw_start_stack =  NULL;

/* Defined in main.c */
#ifdef yy_hlw_STDINIT
    yy_hlwin = stdin;
    yy_hlwout = stdout;
#else
    yy_hlwin = (FILE *) 0;
    yy_hlwout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yy_hlwlex_init()
     */
    return 0;
}

/* yy_hlwlex_destroy is for both reentrant and non-reentrant scanners. */
int yy_hlwlex_destroy  (yy_hlwscan_t yy_hlwscanner)
{
    struct yy_hlwguts_t * yy_hlwg = (struct yy_hlwguts_t*)yy_hlwscanner;

    /* Pop the buffer stack, destroying each element. */
	while(yy_hlw_CURRENT_BUFFER){
		yy_hlw_delete_buffer(yy_hlw_CURRENT_BUFFER ,yy_hlwscanner );
		yy_hlw_CURRENT_BUFFER_LVALUE = NULL;
		yy_hlwpop_buffer_state(yy_hlwscanner);
	}

	/* Destroy the stack itself. */
	yy_hlwfree(yy_hlwg->yy_hlw_buffer_stack ,yy_hlwscanner);
	yy_hlwg->yy_hlw_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yy_hlwfree(yy_hlwg->yy_hlw_start_stack ,yy_hlwscanner );
        yy_hlwg->yy_hlw_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yy_hlwlex() is called, initialization will occur. */
    yy_hlw_init_globals( yy_hlwscanner);

    /* Destroy the main struct (reentrant only). */
    yy_hlwfree ( yy_hlwscanner , yy_hlwscanner );
    yy_hlwscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yy_hlwtext_ptr
static void yy_hlw_flex_strncpy (char* s1, yy_hlwconst char * s2, int n , yy_hlwscan_t yy_hlwscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef yy_hlw_NEED_STRLEN
static int yy_hlw_flex_strlen (yy_hlwconst char * s , yy_hlwscan_t yy_hlwscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yy_hlwalloc (yy_hlw_size_t  size , yy_hlwscan_t yy_hlwscanner)
{
	return (void *) malloc( size );
}

void *yy_hlwrealloc  (void * ptr, yy_hlw_size_t  size , yy_hlwscan_t yy_hlwscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yy_hlwfree (void * ptr , yy_hlwscan_t yy_hlwscanner)
{
	free( (char *) ptr );	/* see yy_hlwrealloc() for (char *) cast */
}

#define yy_hlwTABLES_NAME "yy_hlwtables"

#line 77 "_jsgf_scanner.l"



